// Code generated by "stringer -type=Type"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[ASSIGN-2]
	_ = x[PLUS-3]
	_ = x[HYPHEN-4]
	_ = x[ASTERISK-5]
	_ = x[SLASH-6]
	_ = x[BANG-7]
	_ = x[LT-8]
	_ = x[GT-9]
	_ = x[PERCENT-10]
	_ = x[EQ-11]
	_ = x[NOT_EQ-12]
	_ = x[LTE-13]
	_ = x[GTE-14]
	_ = x[LSHIFT-15]
	_ = x[RSHIFT-16]
	_ = x[PLUS_EQUAL-17]
	_ = x[MINUS_EQUAL-18]
	_ = x[MULTIPLY_EQUAL-19]
	_ = x[DIVIDE_EQUAL-20]
	_ = x[MODULO_EQUAL-21]
	_ = x[INCREMENT-22]
	_ = x[DECREMENT-23]
	_ = x[COMMA-24]
	_ = x[SEMICOLON-25]
	_ = x[LPAREN-26]
	_ = x[RPAREN-27]
	_ = x[LBRACE-28]
	_ = x[RBRACE-29]
	_ = x[LET-30]
	_ = x[IDENT-31]
	_ = x[INT-32]
	_ = x[FUNCTION-33]
	_ = x[IF-34]
	_ = x[ELSE-35]
	_ = x[RETURN-36]
}

const _Type_name = "ILLEGALEOFASSIGNPLUSHYPHENASTERISKSLASHBANGLTGTPERCENTEQNOT_EQLTEGTELSHIFTRSHIFTPLUS_EQUALMINUS_EQUALMULTIPLY_EQUALDIVIDE_EQUALMODULO_EQUALINCREMENTDECREMENTCOMMASEMICOLONLPARENRPARENLBRACERBRACELETIDENTINTFUNCTIONIFELSERETURN"

var _Type_index = [...]uint8{0, 7, 10, 16, 20, 26, 34, 39, 43, 45, 47, 54, 56, 62, 65, 68, 74, 80, 90, 101, 115, 127, 139, 148, 157, 162, 171, 177, 183, 189, 195, 198, 203, 206, 214, 216, 220, 226}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
